#!/usr/bin/env python3

import argparse
import pathlib
import re
import sys


def sanitize_identifier(value: str) -> str:
    identifier = re.sub(r"[^0-9A-Za-z_]", "_", value)
    if not identifier:
        identifier = "embedded_font"
    if identifier[0].isdigit():
        identifier = "_" + identifier
    return identifier


def format_bytes(data: bytes, indent: str = "    ", bytes_per_line: int = 12) -> str:
    lines = []
    for start in range(0, len(data), bytes_per_line):
        chunk = data[start:start + bytes_per_line]
        lines.append(indent + ", ".join(f"0x{byte:02x}" for byte in chunk))
    if not lines:
        lines.append(indent)
    return ",\n".join(lines)


def build_header(array_name: str, data: bytes, source_name: str) -> str:
    size_name = f"{array_name}_size"
    byte_lines = format_bytes(data)
    return f"""#pragma once

#include <stdint.h>

// Generated from {source_name}
static const uint8_t {array_name}[] = {{
{byte_lines}
}};

static const uint64_t {size_name} = sizeof({array_name});
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a TTF file into a C header with an embedded byte array."
    )
    parser.add_argument("input_ttf", help="Path to the input .ttf file")
    parser.add_argument("output_header", help="Path to the generated .h file")
    parser.add_argument(
        "--name",
        help="C identifier to use for the generated byte array (defaults to the input filename stem)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    input_path = pathlib.Path(args.input_ttf)
    output_path = pathlib.Path(args.output_header)

    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 1

    array_name = sanitize_identifier(args.name or input_path.stem)

    data = input_path.read_bytes()
    header_text = build_header(array_name, data, input_path.name)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
